name: generate-and-upload-card

on:
  # Se ejecuta cada 24 horas
  schedule:
    - cron: "0 0 * * *"

  # Permite ejecución manual
  workflow_dispatch:

  # Se ejecuta al pushear a la rama principal
  push:
    branches:
      - main
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate github stats card
        uses: LuciNyan/pixel-profile/action@main
        with:
          outputs: |
            dist/github-stats.png?username=Enzo889&screen_effect=false&theme=monochrome&dithering=true&pixelate_avatar=true&color=%23000000
            dist/github-stats-dark.png?username=Enzo889&theme=crt&screen_effect=true&dithering=true&include_all_commits=true&pixelate_avatar=true&color=%23ffffffFF
          crt_outputs: |
            dist/github-stats-crt.png?username=Enzo889&include_all_commits=true&theme=crt
            
      - name: push cards to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
